### ISSUE TITLE
不打算迁移到1.4.0么

### ISSUE THREAD

**Issue by shitake2333** [LiXiaYu/MVMota#4]
```
RPGMAKER_VERSION = "1.2.0"
```

1.2.0版本有点老啊

**Comment by LiXiaYu** [comment]
...言之有理

**Comment by shitake2333** [comment]
http://github.com/rpgtkoolmv/
这里的是rmmv engine部分的最新版

**Comment by LiXiaYu** [comment]
其实昨天我把MV1.4.0的js覆盖进去了。
这个项目是社区的？跟官方的不太一样吧

**Comment by shitake2333** [comment]
算是官方支持的社区
主力役貌似都是娇喘的
这个项目最后的东西都会跟着rmmv发布出去
